//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestService.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="StatusDetailCollection", Namespace="http://schemas.datacontract.org/2004/07/OdSyncService", ItemName="StatusDetail")]
    [System.SerializableAttribute()]
    public class StatusDetailCollection : System.Collections.Generic.List<TestService.ServiceReference1.StatusDetail> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusDetail", Namespace="http://schemas.datacontract.org/2004/07/OdSyncService")]
    [System.SerializableAttribute()]
    public partial class StatusDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserSIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocalPath {
            get {
                return this.LocalPathField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalPathField, value) != true)) {
                    this.LocalPathField = value;
                    this.RaisePropertyChanged("LocalPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusString {
            get {
                return this.StatusStringField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusStringField, value) != true)) {
                    this.StatusStringField = value;
                    this.RaisePropertyChanged("StatusString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserSID {
            get {
                return this.UserSIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserSIDField, value) != true)) {
                    this.UserSIDField = value;
                    this.RaisePropertyChanged("UserSID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IOdSyncStatusWS")]
    public interface IOdSyncStatusWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOdSyncStatusWS/GetStatus", ReplyAction="http://tempuri.org/IOdSyncStatusWS/GetStatusResponse")]
        TestService.ServiceReference1.StatusDetailCollection GetStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOdSyncStatusWS/GetStatus", ReplyAction="http://tempuri.org/IOdSyncStatusWS/GetStatusResponse")]
        System.Threading.Tasks.Task<TestService.ServiceReference1.StatusDetailCollection> GetStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOdSyncStatusWS/GetOneDetail", ReplyAction="http://tempuri.org/IOdSyncStatusWS/GetOneDetailResponse")]
        TestService.ServiceReference1.StatusDetail GetOneDetail();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOdSyncStatusWS/GetOneDetail", ReplyAction="http://tempuri.org/IOdSyncStatusWS/GetOneDetailResponse")]
        System.Threading.Tasks.Task<TestService.ServiceReference1.StatusDetail> GetOneDetailAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOdSyncStatusWS/GetNumber", ReplyAction="http://tempuri.org/IOdSyncStatusWS/GetNumberResponse")]
        int GetNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOdSyncStatusWS/GetNumber", ReplyAction="http://tempuri.org/IOdSyncStatusWS/GetNumberResponse")]
        System.Threading.Tasks.Task<int> GetNumberAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOdSyncStatusWSChannel : TestService.ServiceReference1.IOdSyncStatusWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OdSyncStatusWSClient : System.ServiceModel.ClientBase<TestService.ServiceReference1.IOdSyncStatusWS>, TestService.ServiceReference1.IOdSyncStatusWS {
        
        public OdSyncStatusWSClient() {
        }
        
        public OdSyncStatusWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OdSyncStatusWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OdSyncStatusWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OdSyncStatusWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestService.ServiceReference1.StatusDetailCollection GetStatus() {
            return base.Channel.GetStatus();
        }
        
        public System.Threading.Tasks.Task<TestService.ServiceReference1.StatusDetailCollection> GetStatusAsync() {
            return base.Channel.GetStatusAsync();
        }
        
        public TestService.ServiceReference1.StatusDetail GetOneDetail() {
            return base.Channel.GetOneDetail();
        }
        
        public System.Threading.Tasks.Task<TestService.ServiceReference1.StatusDetail> GetOneDetailAsync() {
            return base.Channel.GetOneDetailAsync();
        }
        
        public int GetNumber() {
            return base.Channel.GetNumber();
        }
        
        public System.Threading.Tasks.Task<int> GetNumberAsync() {
            return base.Channel.GetNumberAsync();
        }
    }
}
